spring:
  datasource:
    url: jdbc:mysql://localhost:3306/burger_pos?createDatabaseIfNotExist=true
    username: ryan
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: ryan
      password: 1234

  application:
    name: burger
